pipeline {
  agent any
  options {
    buildDiscarder(logRotator(numToKeepStr: '5'))
  }
  environment {
    DOCKERHUB_CREDENTIALS = credentials('dockerhub')
  }
  stages {
    stage('Build') {
      script {
            docker.build("essential_image:latest", "-f Documents/diplom/docker-images/images/essential_image .")
        }
    }
    stage('Login') {
      steps {
        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
      }
    }
    stage('Push') {
      steps {
        sh 'docker push feztix/Jenkins__Doocker__Virtual-Security-Analisys-Lab'
      }
    }
  }
  post {
    always {
      sh 'docker logout'
    }
  }
}
