pipeline {
  agent any
  options {
    buildDiscarder(logRotator(numToKeepStr: '5'))
  }
  environment {
    DOCKERHUB_CREDENTIALS = credentials('dockerhub')
  }
  stages {
    stage('Build') {
    	steps {
	sh 'docker build -t feztix/jenkins-essential-image .'
      }
    }
    stage('Login') {
      steps {
        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
      }
    }
    stage('Push') {
      steps {
        sh 'docker push feztix/Jenkins__Doocker__Virtual-Security-Analisys-Lab'
      }
    }
  }
  post {
    always {
      sh 'docker logout'
    }
  }
}
